import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Nav from "../components/Nav";
import { AuthProvider } from "../context/AuthContext";
import Footer from "../components/Footer";
import { ThemeProvider } from "../components/theme-provider";
import { BlogProvider } from "../context/ContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-30 py-10 flex flex-col justify-center min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <BlogProvider>
              <Nav />
              {children}
              <Footer />
            </BlogProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}